### ISSUE TITLE
Malicious URL: dienste-email.eu

### ISSUE THREAD

**Issue by lolli78** [infobloxopen/threat-intelligence#33]
Hello everyone,
according to https://www.golem.de/news/ukrainekrieg-verfassungsschutz-verschaerft-warnung-vor-cyberangriffen-2203-164124.html and https://www.virustotal.com/gui/domain/dienste-email.eu/detection please add "dienste-email.eu" to the list of malicious domains.
Thank you!

**Comment by chris-kim-agent1** [comment]
Thank you for the intelligence.
